import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Logo from "@/app/img/acunMedyaAkademiLogo.png"


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


export const metadata = {
  title: "Öğrenci Yoklama Sistemi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <div className="header">
          <div className="navLogo">
            <Link href="/">< img src={Logo.src} width={"60px"}></img>
            </Link>
          </div>

          <div className="nav">
            <Link href="/">Yoklama Al</Link>
            <Link href="/hakkimda">Öğrenci İstatistikleri</Link>
            <Link href="/detay">Detay</Link>
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}
